### ISSUE TITLE
hapress.res._removeHeader is undefined

### ISSUE THREAD

**Issue by gr2m** [jakepruitt/hapi-to-express#5]
Hello there 👋 

We use `hapi-to-express` at [Hoodie](https://github.com/hoodiehq/hoodie) so that we can use [express-pouchdb](https://travis-ci.org/pouchdb/express-pouchdb) as a fallback to CouchDB. The code for it is here: https://github.com/hoodiehq/hoodie-store-server/blob/master/index.js#L64-L76

A problem we run into is that `res.removeHeader(name)` throws an error, see https://github.com/expressjs/compression/issues/91. The problem is that `res._removedHeader` is undefined, but it should be an object at all times. I’m no express expert, but I guess it’s passing on Node’s [native response object](https://github.com/nodejs/node/blob/master/lib/_http_outgoing.js) which uses `res._removedHeader` internally.

Here is an example for demonstration

``` js
var Hapi = require('hapi')
var hapiToExpress = require('hapi-to-express')
var express = require('express')
var app = express()

var server = new Hapi.Server()
server.connection({port: 3000})

server.route({
  method: 'GET',
  path: '/',
  handler: function (request, reply) {
    var hapress = hapiToExpress(request, reply)

    app.get('/', function (req, res) {
      res.writeHead(200, {'Content-Type': 'text/plain'})
      res.end('res._removedHeader: ' + res._removedHeader + '\n')
    })

    app(hapress.req, hapress.res)
  }
})

server.start(function (error) {
  if (error) {
    throw error
  }
  console.log(`Server running at: ${server.info.uri}`)
})
```

Is there anything we could do about it?

**Comment by gr2m** [comment]
It seems like implementing the `res.removeHeader` method would do the trick, too

**Comment by gr2m** [comment]
this fixes the problem for us #6, I tested it locally

**Comment by gr2m** [comment]
ping 🔔

**Comment by jakepruitt** [comment]
Oh my gosh, so so sorry @gr2m. Just seeing this now.

Thanks so much for the contribution! Going to merge this and add you as a contributor. If there's anyone else that you want to add as a collaborator, let me know!

**Comment by gr2m** [comment]
Thanks :) Could you also release a new version?

**Comment by jakepruitt** [comment]
Yeah for sure! What's your npm handle? I'll add you over there too 😄

**Comment by gr2m** [comment]
[gr2m](https://www.npmjs.com/~gr2m) :)

**Comment by jakepruitt** [comment]
Done, thanks for the contribution! 🎉
